name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.9
  - dask[complete]
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - gdal
  - xarray
  - rioxarray
  - xarray-spatial
  - matplotlib 
  - h5netcdf
  - zarr
  - pip
  - pip:
    - clustering-geodata-cubes
    - stac2dcache

